{% set name = "autocnet" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/DOI-USGS/Autocnet/archive/refs/tags/{{ version }}.tar.gz
  sha256: 233ec9b333305dbeb105a612a809b5cf8a4391c84d402ea92fe2615ba1cc290b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation 
  noarch: python
  number: 0

requirements:
    host:
      - python >=3.10
      - pip
      - setuptools
    run:
      - python >=3.10
      - csmapi
      - cyvlfeat
      - matplotlib-base
      - dill
      - gdal
      - geoalchemy2
      - geopandas
      - hoggorm
      - imageio
      - ipykernel
      - kalasiris
      - knoten
      - networkx >=2,<3
      - numpy
      - opencv
      - pandas
      - pyyaml
      - plio >=1.5.4
      - plurmy
      - psycopg2
      - pvl >=1.0,<2
      - proj
      - pyproj
      - richdem
      - scikit-image >=0.17
      - scikit-learn
      - scipy
      - shapely
      - sqlalchemy
      - sqlalchemy-utils
      - redis-py <5
      - usgscsm >=2.0.0
      - vlfeat
      - protobuf <=3.20

test:
  imports:
    - autocnet
    - autocnet.graph.network

about:
  home: https://github.com/DOI-USGS/Autocnet
  summary: 'A Python library for automatic generation of control networks for the geodetic control of planetary images.'
  description: 'Automatic control network generation'
  doc_url: https://github.com/DOI-USGS/Autocnet#readme
  dev_url: https://github.com/DOI-USGS/Autocnet
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - Kelvinrr
    - amystamile-usgs
